// src/pages/Contact.vue
<template>
  <div class="max-w-4xl mx-auto px-6 py-12">
    <!-- Hero Section -->
    <div 
      ref="heroRef"
      class="text-center mb-16 transition-all duration-1000 transform"
      :class="[heroVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10']"
    >
      <h1 class="text-4xl md:text-5xl font-bold mb-4 bg-gradient-to-r from-blue-600 to-cyan-500 bg-clip-text text-transparent">
        Liên hệ
      </h1>
      <p class="text-gray-600 dark:text-gray-400 max-w-lg mx-auto">
        Có dự án muốn hợp tác? Hay chỉ muốn nói chuyện về tech? Mình luôn sẵn sàng.
      </p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-12 mb-20">
      <!-- Contact Form Section -->
      <div 
        ref="formRef"
        class="transition-all duration-1000 transform"
        :class="[formVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10']"
      >
        <div v-if="sent" class="bg-white dark:bg-gray-900/50 border border-gray-200 dark:border-gray-800 rounded-2xl p-8 text-center h-full flex flex-col items-center justify-center shadow-sm">
          <div class="w-16 h-16 rounded-full bg-gradient-to-br from-green-500 to-cyan-500 flex items-center justify-center mb-6 animate-bounce">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 13l4 4L19 7" />
            </svg>
          </div>
          <h3 class="text-xl font-bold mb-2">Đã gửi thành công!</h3>
          <p class="text-gray-600 dark:text-gray-400 mb-6">Cảm ơn bạn đã liên hệ. Mình sẽ phản hồi trong vòng 24 giờ.</p>
          <button 
            @click="resetForm"
            class="px-6 py-2 rounded-lg border border-gray-200 dark:border-gray-700 hover:border-blue-500 text-blue-600 dark:text-blue-400 transition-colors"
          >
            Gửi tin nhắn khác
          </button>
        </div>

        <div v-else class="bg-white dark:bg-gray-900/50 border border-gray-200 dark:border-gray-800 rounded-2xl p-8 shadow-sm">
          <h2 class="text-xl font-bold mb-8">Gửi tin nhắn</h2>
          
          <form @submit.prevent="handleSubmit" class="space-y-6">
            <!-- Name Field -->
            <div>
              <label for="name" class="block text-sm font-medium text-gray-700 dark:text-gray-400 mb-2">Tên</label>
              <input 
                id="name"
                v-model="form.name"
                type="text"
                placeholder="Tên của bạn"
                class="w-full bg-transparent border rounded-xl px-4 py-3 outline-none transition-all duration-300 dark:text-white"
                :class="errors.name ? 'border-red-500 focus:ring-2 focus:ring-red-500/20' : 'border-gray-200 dark:border-gray-800 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20'"
              />
              <p v-if="errors.name" class="mt-2 text-sm text-red-500">{{ errors.name }}</p>
            </div>

            <!-- Email Field -->
            <div>
              <label for="email" class="block text-sm font-medium text-gray-700 dark:text-gray-400 mb-2">Email</label>
              <input 
                id="email"
                v-model="form.email"
                type="email"
                placeholder="email@example.com"
                class="w-full bg-transparent border rounded-xl px-4 py-3 outline-none transition-all duration-300 dark:text-white"
                :class="errors.email ? 'border-red-500 focus:ring-2 focus:ring-red-500/20' : 'border-gray-800 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20'"
              />
              <p v-if="errors.email" class="mt-2 text-sm text-red-500">{{ errors.email }}</p>
            </div>

            <!-- Message Field -->
            <div>
              <label for="message" class="block text-sm font-medium text-gray-700 dark:text-gray-400 mb-2">Nội dung</label>
              <textarea 
                id="message"
                v-model="form.message"
                rows="5"
                placeholder="Mình muốn hợp tác về..."
                class="w-full bg-transparent border rounded-xl px-4 py-3 outline-none transition-all duration-300 resize-none dark:text-white"
                :class="errors.message ? 'border-red-500 focus:ring-2 focus:ring-red-500/20' : 'border-gray-200 dark:border-gray-800 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20'"
              ></textarea>
              <p v-if="errors.message" class="mt-2 text-sm text-red-500">{{ errors.message }}</p>
            </div>

            <button 
              type="submit"
              :disabled="sending"
              class="w-full py-4 rounded-xl font-bold transition-all duration-300 transform active:scale-[0.98] flex items-center justify-center gap-2"
              :class="isFormValid ? 'bg-gradient-to-r from-blue-600 to-cyan-600 text-white shadow-lg shadow-blue-500/20 hover:-translate-y-1' : 'bg-gray-100 dark:bg-gray-800 text-gray-400 dark:text-gray-500 cursor-not-allowed'"
            >
              <template v-if="sending">
                <svg class="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                Đang gửi...
              </template>
              <template v-else>
                Gửi tin nhắn
              </template>
            </button>
          </form>
        </div>
      </div>

      <!-- Social Links Section -->
      <div 
        ref="socialRef"
        class="transition-all duration-1000 delay-200 transform"
        :class="[socialVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10']"
      >
        <h2 class="text-xl font-bold mb-6">Kết nối</h2>
        <div class="space-y-4 mb-8">
          <a 
            v-for="social in socials" 
            :key="social.name"
            :href="social.link"
            target="_blank"
            class="flex items-center gap-4 p-4 rounded-xl border border-gray-200 dark:border-gray-800 hover:border-blue-500/50 hover:bg-blue-500/5 transition-all duration-300 group"
          >
            <div 
              class="w-12 h-12 rounded-xl flex items-center justify-center text-xl transition-colors"
              :style="{ backgroundColor: social.color + '10', color: social.color }"
            >
              <i :class="social.icon"></i>
            </div>
            <div class="flex-1">
              <p class="font-bold group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">{{ social.name }}</p>
              <p class="text-sm text-gray-500">{{ social.desc }}</p>
            </div>
            <span class="text-xs font-mono text-gray-400 group-hover:text-blue-600 dark:group-hover:text-blue-400">{{ social.handle }}</span>
          </a>
        </div>

        <!-- Status Card -->
        <div class="p-6 rounded-2xl bg-blue-500/5 border border-blue-100 dark:border-blue-900/30">
          <p class="text-sm font-bold mb-4">Response time</p>
          <div class="flex items-center gap-3 mb-2">
            <div class="w-2 h-2 rounded-full bg-green-500 animate-pulse"></div>
            <span class="text-sm text-gray-600 dark:text-gray-400">Thường phản hồi trong 24 giờ</span>
          </div>
          <p class="text-xs text-gray-500 leading-relaxed">
            Timezone: GMT+7 (Việt Nam). Mình check email và messages hàng ngày.
          </p>
        </div>
      </div>
    </div>

    <!-- CTA Section -->
    <div 
      ref="ctaRef"
      class="bg-gradient-to-br from-blue-600 to-cyan-600 rounded-3xl p-10 text-center text-white relative overflow-hidden group transition-all duration-1000 transform"
      :class="[ctaVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10']"
    >
      <div class="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full -translate-y-1/2 translate-x-1/2 blur-3xl group-hover:bg-white/20 transition-colors duration-500"></div>
      <h3 class="text-2xl font-bold mb-4 relative z-10">Đang tìm Full Stack / DevOps Engineer?</h3>
      <p class="text-white/80 mb-8 max-w-md mx-auto relative z-10">
        Mình luôn open cho các cơ hội thú vị. Hãy kết nối nhé!
      </p>
      <div class="flex flex-wrap justify-center gap-4 relative z-10">
        <a href="/cv.pdf" target="_blank" class="px-8 py-3 bg-white/20 backdrop-blur-md border border-white/30 rounded-xl font-bold hover:bg-white/30 transition-all">
          Xem CV ↓
        </a>
        <a href="https://linkedin.com" target="_blank" class="px-8 py-3 bg-white text-blue-600 rounded-xl font-bold hover:shadow-xl hover:-translate-y-1 transition-all">
          LinkedIn ↗
        </a>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, computed } from 'vue'
import { useScrollReveal } from '../composables/useScrollReveal'

const { targetRef: heroRef, isVisible: heroVisible } = useScrollReveal()
const { targetRef: formRef, isVisible: formVisible } = useScrollReveal()
const { targetRef: socialRef, isVisible: socialVisible } = useScrollReveal()
const { targetRef: ctaRef, isVisible: ctaVisible } = useScrollReveal()

const form = reactive({
  name: '',
  email: '',
  message: ''
})

const errors = reactive({
  name: '',
  email: '',
  message: ''
})

const sent = ref(false)
const sending = ref(false)

const socials = [
  { 
    name: 'GitHub', 
    handle: '@yourname', 
    desc: 'Open source & side projects', 
    color: '#333333', 
    icon: 'fab fa-github',
    link: 'https://github.com'
  },
  { 
    name: 'LinkedIn', 
    handle: 'in/yourname', 
    desc: 'Professional network', 
    color: '#0a66c2', 
    icon: 'fab fa-linkedin',
    link: 'https://linkedin.com'
  },
  { 
    name: 'Twitter', 
    handle: '@yourname', 
    desc: 'Tech thoughts & threads', 
    color: '#1d9bf0', 
    icon: 'fab fa-twitter',
    link: 'https://twitter.com'
  },
  { 
    name: 'Email', 
    handle: 'hello@yourname.dev', 
    desc: 'Liên hệ trực tiếp', 
    color: '#06b6d4', 
    icon: 'fas fa-envelope',
    link: 'mailto:hello@yourname.dev'
  }
]

const validateEmail = (email: string) => {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)
}

const validate = () => {
  let isValid = true
  
  if (!form.name.trim()) {
    errors.name = 'Tên không được để trống.'
    isValid = false
  } else {
    errors.name = ''
  }
  
  if (!form.email.trim()) {
    errors.email = 'Email không được để trống.'
    isValid = false
  } else if (!validateEmail(form.email)) {
    errors.email = 'Định dạng email không hợp lệ.'
    isValid = false
  } else {
    errors.email = ''
  }
  
  if (!form.message.trim()) {
    errors.message = 'Nội dung không được để trống.'
    isValid = false
  } else {
    errors.message = ''
  }
  
  return isValid
}

const isFormValid = computed(() => {
  return form.name.trim() && form.email.trim() && validateEmail(form.email) && form.message.trim()
})

const handleSubmit = async () => {
  if (!validate()) return
  
  sending.value = true
  
  // Simulation of submission - Supabase integration will be in Task 6.2
  try {
    await new Promise(resolve => setTimeout(resolve, 1500))
    sent.value = true
    // Task 6.2: submit to Supabase
  } catch (error) {
    console.error('Submission failed:', error)
  } finally {
    sending.value = false
  }
}

const resetForm = () => {
  form.name = ''
  form.email = ''
  form.message = ''
  errors.name = ''
  errors.email = ''
  errors.message = ''
  sent.value = false
}
</script>

<style scoped>
/* Any specific page transitions or additional custom styles can go here */
</style>

// specs/design/contact.jsx
import { useState, useEffect, useRef } from "react";

function useScrollReveal() {
  const ref = useRef(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setVisible(true); obs.disconnect(); } }, { threshold: 0.15 });
    obs.observe(el);
    return () => obs.disconnect();
  }, []);
  return [ref, visible];
}

function Reveal({ children, delay = 0 }) {
  const [ref, visible] = useScrollReveal();
  return <div ref={ref} style={{ opacity: visible ? 1 : 0, transform: visible ? "translateY(0)" : "translateY(30px)", transition: `opacity 0.6s ease ${delay}s, transform 0.6s ease ${delay}s` }}>{children}</div>;
}

const SOCIALS = [
  { name: "GitHub", handle: "@yourname", desc: "Open source & side projects", color: "#333", icon: "⬡" },
  { name: "LinkedIn", handle: "in/yourname", desc: "Professional network", color: "#0a66c2", icon: "◆" },
  { name: "Twitter", handle: "@yourname", desc: "Tech thoughts & threads", color: "#1d9bf0", icon: "◇" },
  { name: "Email", handle: "hello@yourname.dev", desc: "Liên hệ trực tiếp", color: "#06b6d4", icon: "✉" },
];

export default function ContactPage() {
  const [dark, setDark] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", message: "" });
  const [focused, setFocused] = useState(null);
  const [sent, setSent] = useState(false);
  const [sending, setSending] = useState(false);

  const handleSubmit = () => {
    if (!form.name || !form.email || !form.message) return;
    setSending(true);
    setTimeout(() => { setSending(false); setSent(true); }, 1500);
  };

  const root = {
    "--bg": dark ? "#0a0e17" : "#fafbfc",
    "--bg2": dark ? "#111827" : "#f1f3f6",
    "--text": dark ? "#e2e8f0" : "#1a202c",
    "--text2": dark ? "#94a3b8" : "#64748b",
    "--border": dark ? "rgba(148,163,184,0.12)" : "rgba(0,0,0,0.08)",
    "--accent": "#3b82f6",
    "--accent2": "#06b6d4",
  };

  const inputStyle = (field) => ({
    width: "100%",
    padding: "12px 16px",
    borderRadius: 10,
    border: "0.5px solid " + (focused === field ? "var(--accent)" : "var(--border)"),
    background: "transparent",
    color: "var(--text)",
    fontSize: 14,
    fontFamily: "'DM Sans', sans-serif",
    outline: "none",
    transition: "border-color 0.3s, box-shadow 0.3s",
    boxShadow: focused === field ? (dark ? "0 0 0 3px rgba(59,130,246,0.12)" : "0 0 0 3px rgba(59,130,246,0.08)") : "none",
  });

  return (
    <div style={{ ...root, background: "var(--bg)", color: "var(--text)", minHeight: "100vh", fontFamily: "'DM Sans', sans-serif", transition: "background 0.4s" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=JetBrains+Mono:wght@400;500&display=swap');
        * { margin:0;padding:0;box-sizing:border-box; }
        @keyframes pulse { 0%,100% { opacity: 1; } 50% { opacity: 0.5; } }
        @keyframes checkmark { 0% { transform: scale(0) rotate(-45deg); opacity: 0; } 50% { transform: scale(1.2) rotate(-45deg); } 100% { transform: scale(1) rotate(0deg); opacity: 1; } }
      `}</style>

      <nav style={{ position: "sticky", top: 0, zIndex: 50, backdropFilter: "blur(20px)", background: dark ? "rgba(10,14,23,0.8)" : "rgba(250,251,252,0.85)", borderBottom: "0.5px solid var(--border)" }}>
        <div style={{ maxWidth: 900, margin: "0 auto", padding: "14px 32px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <span style={{ fontWeight: 700, fontSize: 17, letterSpacing: -0.8, background: "linear-gradient(135deg, var(--accent), var(--accent2))", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>your.name</span>
          <div style={{ display: "flex", alignItems: "center", gap: 24 }}>
            {["about", "projects", "blog", "contact"].map(l => (
              <span key={l} style={{ fontSize: 13, color: l === "contact" ? "var(--accent)" : "var(--text2)", cursor: "pointer", fontWeight: l === "contact" ? 600 : 500 }}>{l}</span>
            ))}
            <button onClick={() => setDark(!dark)} style={{ width: 32, height: 32, borderRadius: "50%", border: "0.5px solid var(--border)", background: "transparent", cursor: "pointer", fontSize: 14, display: "flex", alignItems: "center", justifyContent: "center", color: "var(--text2)" }}>{dark ? "☀" : "☾"}</button>
          </div>
        </div>
      </nav>

      <div style={{ maxWidth: 900, margin: "0 auto", padding: "0 32px" }}>
        <Reveal>
          <div style={{ padding: "60px 0 40px", textAlign: "center" }}>
            <h1 style={{ fontSize: 28, fontWeight: 700, letterSpacing: -1, marginBottom: 8 }}>Liên hệ</h1>
            <p style={{ fontSize: 14, color: "var(--text2)", maxWidth: 440, margin: "0 auto" }}>Có dự án muốn hợp tác? Hay chỉ muốn nói chuyện về tech? Mình luôn sẵn sàng.</p>
          </div>
        </Reveal>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 32, marginBottom: 60 }}>
          <Reveal>
            <div>
              {sent ? (
                <div style={{ padding: "80px 32px", borderRadius: 16, border: "0.5px solid var(--border)", background: dark ? "rgba(17,24,39,0.5)" : "rgba(255,255,255,0.7)", textAlign: "center" }}>
                  <div style={{ width: 64, height: 64, borderRadius: "50%", background: "linear-gradient(135deg, #22c55e, #06b6d4)", margin: "0 auto 20px", display: "flex", alignItems: "center", justifyContent: "center", animation: "checkmark 0.5s ease" }}>
                    <span style={{ fontSize: 28, color: "#fff" }}>✓</span>
                  </div>
                  <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 8 }}>Đã gửi thành công!</h3>
                  <p style={{ fontSize: 13, color: "var(--text2)", lineHeight: 1.6, marginBottom: 20 }}>Cảm ơn bạn đã liên hệ. Mình sẽ phản hồi trong vòng 24 giờ.</p>
                  <button onClick={() => { setSent(false); setForm({ name: "", email: "", message: "" }); }} style={{ fontSize: 13, padding: "8px 20px", borderRadius: 8, border: "0.5px solid var(--border)", background: "transparent", color: "var(--accent)", cursor: "pointer", fontWeight: 500 }}>Gửi tin nhắn khác</button>
                </div>
              ) : (
                <div style={{ padding: "28px 32px", borderRadius: 16, border: "0.5px solid var(--border)", background: dark ? "rgba(17,24,39,0.5)" : "rgba(255,255,255,0.7)" }}>
                  <h2 style={{ fontSize: 16, fontWeight: 600, marginBottom: 24 }}>Gửi tin nhắn</h2>

                  <div style={{ marginBottom: 18 }}>
                    <label style={{ fontSize: 12, fontWeight: 500, color: "var(--text2)", display: "block", marginBottom: 6 }}>Tên</label>
                    <input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} onFocus={() => setFocused("name")} onBlur={() => setFocused(null)} placeholder="Tên của bạn" style={inputStyle("name")} />
                  </div>

                  <div style={{ marginBottom: 18 }}>
                    <label style={{ fontSize: 12, fontWeight: 500, color: "var(--text2)", display: "block", marginBottom: 6 }}>Email</label>
                    <input value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} onFocus={() => setFocused("email")} onBlur={() => setFocused(null)} placeholder="email@example.com" style={inputStyle("email")} />
                  </div>

                  <div style={{ marginBottom: 24 }}>
                    <label style={{ fontSize: 12, fontWeight: 500, color: "var(--text2)", display: "block", marginBottom: 6 }}>Nội dung</label>
                    <textarea value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} onFocus={() => setFocused("message")} onBlur={() => setFocused(null)} placeholder="Mình muốn hợp tác về..." rows={5} style={{ ...inputStyle("message"), resize: "vertical", minHeight: 120 }} />
                  </div>

                  <button onClick={handleSubmit} disabled={sending || !form.name || !form.email || !form.message} style={{ width: "100%", padding: "12px", borderRadius: 10, border: "none", background: (form.name && form.email && form.message) ? "linear-gradient(135deg, var(--accent), var(--accent2))" : "var(--bg2)", color: (form.name && form.email && form.message) ? "#fff" : "var(--text2)", fontSize: 14, fontWeight: 600, cursor: (form.name && form.email && form.message) ? "pointer" : "not-allowed", transition: "all 0.3s", fontFamily: "'DM Sans', sans-serif", opacity: sending ? 0.7 : 1 }}
                    onMouseEnter={e => { if (form.name && form.email && form.message && !sending) { e.target.style.transform = "translateY(-2px)"; e.target.style.boxShadow = "0 8px 24px rgba(59,130,246,0.3)"; } }}
                    onMouseLeave={e => { e.target.style.transform = "translateY(0)"; e.target.style.boxShadow = "none"; }}>
                    {sending ? (
                      <span style={{ animation: "pulse 1s infinite" }}>Đang gửi...</span>
                    ) : "Gửi tin nhắn"}
                  </button>
                </div>
              )}
            </div>
          </Reveal>

          <Reveal delay={0.15}>
            <div>
              <h2 style={{ fontSize: 16, fontWeight: 600, marginBottom: 16 }}>Kết nối</h2>
              <div style={{ display: "flex", flexDirection: "column", gap: 10, marginBottom: 32 }}>
                {SOCIALS.map((s, i) => (
                  <div key={i} style={{ display: "flex", alignItems: "center", gap: 14, padding: "14px 18px", borderRadius: 12, border: "0.5px solid var(--border)", cursor: "pointer", transition: "all 0.3s" }}
                    onMouseEnter={e => { e.currentTarget.style.borderColor = s.color; e.currentTarget.style.transform = "translateX(4px)"; }}
                    onMouseLeave={e => { e.currentTarget.style.borderColor = "var(--border)"; e.currentTarget.style.transform = "translateX(0)"; }}>
                    <div style={{ width: 40, height: 40, borderRadius: 10, background: s.color + "14", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16, color: s.color, flexShrink: 0 }}>{s.icon}</div>
                    <div style={{ flex: 1 }}>
                      <p style={{ fontSize: 14, fontWeight: 600, marginBottom: 1 }}>{s.name}</p>
                      <p style={{ fontSize: 12, color: "var(--text2)" }}>{s.desc}</p>
                    </div>
                    <span style={{ fontSize: 12, color: s.color, fontFamily: "'JetBrains Mono', monospace", fontWeight: 500 }}>{s.handle}</span>
                  </div>
                ))}
              </div>

              <div style={{ padding: "24px", borderRadius: 14, background: dark ? "rgba(59,130,246,0.06)" : "rgba(59,130,246,0.03)", border: "0.5px solid var(--border)" }}>
                <p style={{ fontSize: 13, fontWeight: 600, marginBottom: 8 }}>Response time</p>
                <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
                  <div style={{ width: 8, height: 8, borderRadius: "50%", background: "#22c55e" }} />
                  <span style={{ fontSize: 13, color: "var(--text2)" }}>Thường phản hồi trong 24 giờ</span>
                </div>
                <p style={{ fontSize: 12, color: "var(--text2)", marginTop: 8, lineHeight: 1.6 }}>Timezone: GMT+7 (Việt Nam). Mình check email và messages hàng ngày.</p>
              </div>
            </div>
          </Reveal>
        </div>

        <Reveal>
          <div style={{ padding: "40px", borderRadius: 16, background: "linear-gradient(135deg, var(--accent), var(--accent2))", marginBottom: 60, textAlign: "center" }}>
            <h3 style={{ fontSize: 20, fontWeight: 700, color: "#fff", marginBottom: 8 }}>Đang tìm Full Stack / DevOps Engineer?</h3>
            <p style={{ fontSize: 14, color: "rgba(255,255,255,0.75)", marginBottom: 20, maxWidth: 400, margin: "0 auto 20px" }}>Mình luôn open cho các cơ hội thú vị. Hãy kết nối nhé!</p>
            <div style={{ display: "flex", gap: 12, justifyContent: "center" }}>
              <span style={{ fontSize: 13, padding: "10px 24px", borderRadius: 8, background: "rgba(255,255,255,0.2)", border: "1px solid rgba(255,255,255,0.3)", color: "#fff", fontWeight: 600, cursor: "pointer", backdropFilter: "blur(8px)" }}>Xem CV ↓</span>
              <span style={{ fontSize: 13, padding: "10px 24px", borderRadius: 8, background: "#fff", color: "var(--accent)", fontWeight: 600, cursor: "pointer" }}>LinkedIn ↗</span>
            </div>
          </div>
        </Reveal>

        <footer style={{ padding: "40px 0", borderTop: "0.5px solid var(--border)", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <span style={{ fontSize: 12, color: "var(--text2)" }}>© 2026 your.name</span>
          <div style={{ display: "flex", gap: 20 }}>
            {["GitHub", "LinkedIn", "Twitter"].map(s => (<span key={s} style={{ fontSize: 12, color: "var(--text2)", cursor: "pointer" }}>{s}</span>))}
          </div>
        </footer>
      </div>
    </div>
  );
}
